### ISSUE TITLE
[Feature] Roslyn Source Generators

### ISSUE THREAD

**Issue by adamradocz** [reactiveui/ReactiveObject.Generators#1]
I'm thinking about creating a source generator for the ReactiveUI project, similar to the [CommunityToolkit.Mvvm.SourceGenerators](https://github.com/CommunityToolkit/dotnet/issues/8).

My ideas are the following:

### ReactiveUI Property Source Generator

```csharp
[ReactiveProperty]
private DateTime _time;
```

Generates:

```csharp
public DateTime Time
{
    get => _time;
    set => this.RaiseAndSetIfChanged(ref _time, value);
}
```

### Observable As Property Helper Source Generator

```csharp
[OaphProperty]
private readonly ObservableAsPropertyHelper<string> _text;
```

Generates:

```csharp
public string Text => _text.Value;
```

I'm also considering that only the `[ReactiveProperty]` should be used and generate the appropriate property based on the type.

### DinamicData Property Source Generator

```csharp
[BindingProperty]
private readonly ReadOnlyObservableCollection<TrackViewModel> _tracks;
```

Generates:

```csharp
public ReadOnlyObservableCollection<TrackViewModel> InboundTracks => _tracks; 
```

---

Any idea?

**Comment by glennawatson** [comment]
Transferred over to this repo where work will start on this feature.

**Comment by glennawatson** [comment]
Yeah definitely if you guys want to brainstorm ideas of how the syntax looks in this repo. 

Generators are definitely more limited syntax wise compared to the old fody, but way easier to maintain.

With regards to syntax its best to build a prototype I find with a "partial" class and then put the generated code into the partial class, and see if it works.

**Comment by J-Swift** [comment]
Just a heads up that I am pretty sure the current Fody solution is causing issues in a Maui app I'm working on. I am still investigating, but my theory is that the IL.emit stuff doesn't play nicely w/ whatever has changed in the .net AOT side of things.

**Comment by tothalexlaszlo** [comment]
> Hold off on this for a little while. We already have stuff in the works.

any news on this project?

**Comment by glennawatson** [comment]
Still some work to be done, thanks to @adamradocz for getting the call rolling. 

We had some discussions internally about slightly different directions so will adjust the code accordingly.

**Comment by J-Swift** [comment]
Really happy to see this work merged in! Thank you for the effort @adamradocz!

Question @glennawatson: is the plan to distribute this as a separate nuget artifact? If so, what can I keep an eye on to get that? Or would it be rolled up into another project (e.g. ReactiveUI proper)?
